# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
jobs:
  build:
    docker:

      - image: circleci/node:11.7

    steps:
      - checkout

      - run: echo "hello"